version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes: []
    environment:
      - GIN_MODE=release

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: []
    ports:
      - "80:80"
